#include "RoseQuest.h"
#include "RoseCharacter.h"
#include "RoseGameInstance.h"
#include "RoseSkillComponent.h"
#include "RoseDrops.h"
#include "RoseUIChat.h"
#include "Kismet/GameplayStatics.h"
#include "Misc/FileHelper.h"
#include "Misc/PackageName.h"
#include "Misc/Paths.h"
#include "Serialization/JsonReader.h"
#include "Serialization/JsonSerializer.h"
#include "Dom/JsonObject.h"

DEFINE_LOG_CATEGORY_STATIC(LogRoseQuest, Log, All);

// ─── the shared trigger database (quests.json) ──────────────────────────────
namespace
{
	struct FQuestDB
	{
		TMap<FString, TSharedPtr<FJsonObject>> Triggers;
		bool bLoaded = false;

		static FQuestDB& Get()
		{
			static FQuestDB DB;
			if (!DB.bLoaded)
			{
				DB.bLoaded = true;
				const FString Path = FPaths::ProjectContentDir() / TEXT("Quests/quests.json");
				FString Raw;
				if (!FFileHelper::LoadFileToString(Raw, *Path))
				{
					UE_LOG(LogRoseQuest, Error, TEXT("quests.json missing at %s"), *Path);
					return DB;
				}
				TSharedPtr<FJsonObject> Root;
				const TSharedRef<TJsonReader<>> Reader = TJsonReaderFactory<>::Create(Raw);
				if (!FJsonSerializer::Deserialize(Reader, Root) || !Root.IsValid())
				{
					UE_LOG(LogRoseQuest, Error, TEXT("quests.json parse failed"));
					return DB;
				}
				const TSharedPtr<FJsonObject>* Trigs;
				if (Root->TryGetObjectField(TEXT("triggers"), Trigs))
				{
					for (const auto& Pair : (*Trigs)->Values)
					{
						TSharedPtr<FJsonObject> Obj = Pair.Value->AsObject();
						if (Obj.IsValid())
							DB.Triggers.Add(FString(Pair.Key), Obj);
					}
				}
				UE_LOG(LogRoseQuest, Log, TEXT("quest DB: %d triggers"), DB.Triggers.Num());
			}
			return DB;
		}
	};

	// zone id (LIST_ZONE row, as QSD/WARP.STB reference zones) -> level key.
	// Generated by tools/gen_zone_table.py -> Content/Quests/zones.json.
	struct FZoneTable
	{
		TMap<int32, FString> Keys;
		bool bLoaded = false;

		static FZoneTable& Get()
		{
			static FZoneTable T;
			if (!T.bLoaded)
			{
				T.bLoaded = true;
				const FString Path = FPaths::ProjectContentDir() / TEXT("Quests/zones.json");
				FString Raw;
				TSharedPtr<FJsonObject> Root;
				if (FFileHelper::LoadFileToString(Raw, *Path)
					&& FJsonSerializer::Deserialize(TJsonReaderFactory<>::Create(Raw), Root)
					&& Root.IsValid())
					for (const auto& Pair : Root->Values)
						T.Keys.Add(FCString::Atoi(*Pair.Key), Pair.Value->AsString());
				UE_LOG(LogRoseQuest, Log, TEXT("zones.json: %d zones"), T.Keys.Num());
			}
			return T;
		}
	};

	int32 JInt(const TSharedPtr<FJsonObject>& O, const TCHAR* Field, int32 Default = 0)
	{
		int32 V = Default;
		if (O.IsValid()) O->TryGetNumberField(Field, V);
		return V;
	}

	FString JStr(const TSharedPtr<FJsonObject>& O, const TCHAR* Field)
	{
		FString V;
		if (O.IsValid()) O->TryGetStringField(Field, V);
		return V;
	}

	// Iterate an entity's object-array field ("vars"/"abils"/"items").
	bool JArray(const TSharedPtr<FJsonObject>& O, const TCHAR* Field,
		const TArray<TSharedPtr<FJsonValue>>*& Out)
	{
		return O.IsValid() && O->TryGetArrayField(Field, Out);
	}

	// Get_WorldREWARD — the live server's reward rate; the port bakes 100%.
	constexpr int32 kWorldReward = 100;
}

// ─── component ───────────────────────────────────────────────────────────────
URoseQuestComponent::URoseQuestComponent()
{
	PrimaryComponentTick.bCanEverTick = false;
	Slots.SetNum(10);
	for (FRoseQuestSlot& S : Slots) S.Reset();
	EpisodeVars.Init(0, 5);
	JobVars.Init(0, 3);
	PlanetVars.Init(0, 7);
	UnionVars.Init(0, 10);
	UnionPoints.Init(0, 10);
	Switches.Init(false, 512);
}

void URoseQuestComponent::BeginPlay()
{
	Super::BeginPlay();
	if (!QuestTable)
		QuestTable = LoadObject<UDataTable>(nullptr, TEXT("/Game/DataTables/quests.quests"));
	FQuestDB::Get();   // warm the trigger DB (logs the count once)
}

ARoseCharacter* URoseQuestComponent::OwnerChar() const
{
	return Cast<ARoseCharacter>(GetOwner());
}

const FRoseQuestRow* URoseQuestComponent::GetQuestRow(int32 QuestId) const
{
	if (!QuestTable) return nullptr;
	return QuestTable->FindRow<FRoseQuestRow>(
		*FString::Printf(TEXT("quest_%d"), QuestId), TEXT("RoseQuest"), false);
}

void URoseQuestComponent::Msg(const FString& Text) const
{
	FRoseChatLog::Add(FRoseChatLog::EKind::System, Text);
}

// ─── slot helpers ────────────────────────────────────────────────────────────
int32 URoseQuestComponent::FindQuestSlot(int32 QuestId) const
{
	if (!QuestId) return -1;
	for (int32 i = 0; i < Slots.Num(); ++i)
		if (Slots[i].Id == QuestId) return i;
	return -1;
}

int32 URoseQuestComponent::AppendQuest(int32 QuestId)
{
	if (!QuestId) return -1;
	// Quest_Append: re-registering resets the slot; else first free slot.
	int32 Idx = FindQuestSlot(QuestId);
	if (Idx < 0)
		for (int32 i = 0; i < Slots.Num(); ++i)
			if (Slots[i].Id == 0) { Idx = i; break; }
	if (Idx < 0) return -1;

	Slots[Idx].Reset();
	Slots[Idx].Id = QuestId;
	if (const FRoseQuestRow* Row = GetQuestRow(QuestId))
	{
		if (Row->TimeLimit > 0 && GetWorld())
			Slots[Idx].ExpireAt = GetWorld()->GetTimeSeconds() + Row->TimeLimit;
		if (!Row->StartMsg.IsEmpty())
			Msg(Row->StartMsg);
		else if (!Row->DisplayName.IsEmpty())
			Msg(FString::Printf(TEXT("Quest started: %s"), *Row->DisplayName));
	}
	QuestRevision++;
	return Idx;
}

bool URoseQuestComponent::DeleteQuest(int32 QuestId)
{
	const int32 Idx = FindQuestSlot(QuestId);
	if (Idx < 0) return false;
	Slots[Idx].Reset();
	QuestRevision++;
	return true;
}

int32 URoseQuestComponent::QuestItemQuantity(int32 QuestId, int32 ItemSN) const
{
	const int32 Idx = FindQuestSlot(QuestId);
	if (Idx < 0) return 0;
	for (const FRoseQuestItem& It : Slots[Idx].Items)
		if (It.ItemSN == ItemSN) return It.Quantity;
	return 0;
}

// ─── Lua accessors ───────────────────────────────────────────────────────────
int32 URoseQuestComponent::GetUserSwitch(int32 SwitchNo) const
{
	return (SwitchNo >= 0 && SwitchNo < Switches.Num()) ? (Switches[SwitchNo] ? 1 : 0) : -1;
}
int32 URoseQuestComponent::GetEpisodeVar(int32 VarNo) const
{
	return EpisodeVars.IsValidIndex(VarNo) ? EpisodeVars[VarNo] : 0;
}
int32 URoseQuestComponent::GetJobVar(int32 VarNo) const
{
	return JobVars.IsValidIndex(VarNo) ? JobVars[VarNo] : 0;
}
int32 URoseQuestComponent::GetPlanetVar(int32 VarNo) const
{
	return PlanetVars.IsValidIndex(VarNo) ? PlanetVars[VarNo] : 0;
}
int32 URoseQuestComponent::GetUnionVar(int32 VarNo) const
{
	return UnionVars.IsValidIndex(VarNo) ? UnionVars[VarNo] : 0;
}
int32 URoseQuestComponent::GetQuestVarBySlot(int32 SlotIdx, int32 VarNo) const
{
	if (!Slots.IsValidIndex(SlotIdx) || !Slots[SlotIdx].Vars.IsValidIndex(VarNo)) return 0;
	return Slots[SlotIdx].Vars[VarNo];
}
int32 URoseQuestComponent::GetQuestSwitchBySlot(int32 SlotIdx, int32 SwitchNo) const
{
	if (!Slots.IsValidIndex(SlotIdx) || SwitchNo < 0 || SwitchNo >= 32) return 0;
	return (Slots[SlotIdx].Switches >> SwitchNo) & 1;
}

// ─── comparisons + var plumbing ──────────────────────────────────────────────
bool URoseQuestComponent::CheckOp(int32 Op, int64 Left, int64 Right)
{
	switch (Op)
	{
	case 0:  return Left == Right;
	case 1:  return Left >  Right;
	case 2:  return Left >= Right;
	case 3:  return Left <  Right;
	case 4:  return Left <= Right;
	case 10: return Left != Right;
	default:
		UE_LOG(LogRoseQuest, Warning, TEXT("CheckOp: unknown op %d"), Op);
		return false;
	}
}

int32 URoseQuestComponent::GetQuestVar(const FParam& Param, int32 VarType, int32 VarNo) const
{
	// QST_VARTYPE_* live in the high byte (io_quest.h:11).
	switch (VarType)
	{
	case 0x0000: // VAR
		if (Param.SlotIdx < 0) return VarReadFailed;
		return GetQuestVarBySlot(Param.SlotIdx, VarNo);
	case 0x0100: // SWITCH
		if (Param.SlotIdx < 0) return VarReadFailed;
		return GetQuestSwitchBySlot(Param.SlotIdx, VarNo);
	case 0x0200: // TIMER (remaining seconds)
	{
		if (Param.SlotIdx < 0 || !Slots.IsValidIndex(Param.SlotIdx)) return VarReadFailed;
		const double ExpireAt = Slots[Param.SlotIdx].ExpireAt;
		if (ExpireAt <= 0.0 || !GetWorld()) return 0;
		return FMath::Max(0, int32(ExpireAt - GetWorld()->GetTimeSeconds()));
	}
	case 0x0300: return GetEpisodeVar(VarNo);
	case 0x0400: return GetJobVar(VarNo);
	case 0x0500: return GetPlanetVar(VarNo);
	case 0x0600: return GetUnionVar(VarNo);
	}
	return VarReadFailed;
}

void URoseQuestComponent::SetQuestVar(FParam& Param, int32 VarType, int32 VarNo, int32 Value)
{
	switch (VarType)
	{
	case 0x0000:
		if (Param.SlotIdx >= 0 && Slots.IsValidIndex(Param.SlotIdx)
			&& Slots[Param.SlotIdx].Vars.IsValidIndex(VarNo))
			Slots[Param.SlotIdx].Vars[VarNo] = Value;
		break;
	case 0x0100:
		if (Param.SlotIdx >= 0 && Slots.IsValidIndex(Param.SlotIdx) && VarNo >= 0 && VarNo < 32)
		{
			if (Value) Slots[Param.SlotIdx].Switches |= (1 << VarNo);
			else       Slots[Param.SlotIdx].Switches &= ~(1 << VarNo);
		}
		break;
	case 0x0300: if (EpisodeVars.IsValidIndex(VarNo)) EpisodeVars[VarNo] = Value; break;
	case 0x0400: if (JobVars.IsValidIndex(VarNo))     JobVars[VarNo] = Value;     break;
	case 0x0500: if (PlanetVars.IsValidIndex(VarNo))  PlanetVars[VarNo] = Value;  break;
	case 0x0600: if (UnionVars.IsValidIndex(VarNo))   UnionVars[VarNo] = Value;   break;
	default:
		UE_LOG(LogRoseQuest, Warning, TEXT("SetQuestVar: bad varType %#x"), VarType);
	}
	QuestRevision++;
}

// ─── abilities (Check_UserVAR / Reward_ABILITY subset the QSD data uses) ─────
int32 URoseQuestComponent::GetAbility(int32 AbilType) const
{
	ARoseCharacter* C = OwnerChar();
	if (!C) return 0;
	URoseSkillComponent* Sk = C->FindComponentByClass<URoseSkillComponent>();

	switch (AbilType)
	{
	case 2:  return C->Gender == TEXT("Female") ? 1 : 0;      // AT_SEX
	case 5:  return 0;                                        // AT_UNION (none yet)
	case 8:  return C->GetEquippedId(TEXT("face"));           // AT_FACE
	case 9:  return C->GetEquippedId(TEXT("hair"));           // AT_HAIR
	case 31: return C->Level;                                 // AT_LEVEL
	case 34: return 0;                                        // AT_TEAM_NO
	case 37: return Sk ? Sk->SkillPoints : 0;                 // AT_SKILLPOINT
	case 40: return C->GetZuly();                             // AT_MONEY
	default:
		if (AbilType >= 81 && AbilType <= 90)                 // AT_UNION_POINT1..10
			return UnionPoints[AbilType - 81];
		// STR..SENSE / LEVEL etc. fall through to the character's table.
		return C->GetAbilityValue(AbilType);
	}
}

void URoseQuestComponent::AddAbility(int32 AbilType, int32 Value, bool bSet)
{
	ARoseCharacter* C = OwnerChar();
	if (!C) return;
	URoseSkillComponent* Sk = C->FindComponentByClass<URoseSkillComponent>();

	switch (AbilType)
	{
	case 4:   // AT_CLASS — THE job change (the server does jobs via quests)
		if (Sk && bSet)
		{
			Sk->SetJob(Value);
			Msg(FString::Printf(TEXT("You are now job %d!"), Value));
		}
		break;
	case 30:  // AT_EXP
		Msg(FString::Printf(TEXT("Gained %d experience."), Value));
		// No EXP pool yet — reward logged until the level system lands.
		break;
	case 32:  // AT_BONUSPOINT
		Msg(FString::Printf(TEXT("Gained %d stat points."), Value));
		break;
	case 37:  // AT_SKILLPOINT
		if (Sk) Sk->SkillPoints = bSet ? Value : Sk->SkillPoints + Value;
		break;
	case 40:  // AT_MONEY
		if (bSet) C->AddZuly(Value - C->GetZuly());
		else      C->AddZuly(Value);
		break;
	default:
		if (AbilType >= 81 && AbilType <= 90)
		{
			int32& P = UnionPoints[AbilType - 81];
			P = bSet ? Value : P + Value;
		}
		else
			UE_LOG(LogRoseQuest, Warning,
				TEXT("Reward_ABILITY: unhandled ability %d (%+d)"), AbilType, Value);
	}
	QuestRevision++;
}

// CCal::Get_RewardVALUE (calculation.cpp:78).
int32 URoseQuestComponent::RewardValue(int32 Equation, int32 Base, int32 DupCnt) const
{
	ARoseCharacter* C = OwnerChar();
	if (!C) return 0;
	const int64 Charm = C->Charm, Level = FMath::Max(1, C->Level), Fame = 0;

	switch (Equation)
	{
	case 0: // exp, base-value weighted
		return int32(((Base + 30) * (Charm + 10) * kWorldReward * (Fame + 20))
			/ (Level + 70) / 30000 + Base);
	case 1: // exp, level ratio
		return int32(int64(Base) * (Level + 3) * (Level + Charm / 2 + 40) * kWorldReward / 10000);
	case 2: // money × count
		return Base * DupCnt;
	case 3: // money base  /  5: item base
	case 5:
		return int32(((Base + 20) * (Charm + 10) * kWorldReward * (Fame + 20))
			/ (Level + 70) / 30000 + Base);
	case 4: // money level ratio
		return int32(int64(Base + 2) * (Level + Charm + 40) * (Fame + 40) * kWorldReward / 140000);
	case 6: // item level ratio
		return int32(int64(Base + 20) * (Level + Charm) * (Fame + 20) * kWorldReward / 3000000 + Base);
	}
	return 0;
}

// ─── items ───────────────────────────────────────────────────────────────────
bool URoseQuestComponent::HasItemCheck(const TSharedPtr<FJsonObject>& ItemCheck, FParam& Param) const
{
	ARoseCharacter* C = OwnerChar();
	if (!C) return false;

	const int32 ItemSN = JInt(ItemCheck, TEXT("itemSN"));
	const int32 Where = JInt(ItemCheck, TEXT("where"));
	const int32 Count = JInt(ItemCheck, TEXT("count"));
	const int32 Op = JInt(ItemCheck, TEXT("op"));
	const int32 Type = ItemSN / 1000, No = ItemSN % 1000;
	const FString Slot = RoseItemTypeToSlot(Type);

	if (Where >= 1 && Where < 12)
	{
		// Equipped check (EQUIP_IDX order, datatype.h:303).
		static const TCHAR* EquipSlots[12] = {
			TEXT(""), TEXT("faceitem"), TEXT("cap"), TEXT("body"), TEXT("back"),
			TEXT("arms"), TEXT("foot"), TEXT("weapon"), TEXT("subwpn"),
			TEXT("necklace"), TEXT("ring"), TEXT("earring") };
		return C->GetEquippedId(EquipSlots[Where]) == No && EquipSlots[Where] == Slot;
	}

	if (Type == 13)   // ITEM_TYPE_QUEST → quest inventory of the selected slot
	{
		if (Param.SlotIdx < 0) return false;
		int32 Have = 0;
		for (const FRoseQuestItem& It : Slots[Param.SlotIdx].Items)
			if (It.ItemSN == ItemSN) { Have = It.Quantity; break; }
		return CheckOp(Op, Have, Count);
	}

	// Normal inventory: stacks compare quantity; equipment counts as 1.
	int32 Have = 0;
	for (const FRoseItemStack& St : C->Bag)
		if (St.Slot == Slot && St.Id == No)
			Have += RoseIsStackableSlot(Slot) ? St.Count : 1;
	return CheckOp(Op, Have, Count);
}

bool URoseQuestComponent::GiveOrTakeItem(int32 ItemSN, int32 Count, bool bGive, FParam& Param)
{
	ARoseCharacter* C = OwnerChar();
	if (!C || !ItemSN) return false;
	const int32 Type = ItemSN / 1000, No = ItemSN % 1000;
	const FString Slot = RoseItemTypeToSlot(Type);
	Count = FMath::Max(1, Count);

	if (Type == 13)   // quest item → the selected quest slot's inventory
	{
		if (Param.SlotIdx < 0 || !Slots.IsValidIndex(Param.SlotIdx)) return false;
		TArray<FRoseQuestItem>& Items = Slots[Param.SlotIdx].Items;
		for (int32 i = 0; i < Items.Num(); ++i)
		{
			if (Items[i].ItemSN != ItemSN) continue;
			Items[i].Quantity += bGive ? Count : -Count;
			if (Items[i].Quantity <= 0) Items.RemoveAt(i);
			QuestRevision++;
			return true;
		}
		if (!bGive) return false;
		if (Items.Num() >= 6) return false;    // QUEST_ITEM_PER_QUEST
		Items.Add({ ItemSN, Count });
		Msg(FString::Printf(TEXT("Got quest item: %s"), *C->GetItemName(TEXT("quest"), No)));
		QuestRevision++;
		return true;
	}

	if (bGive)
	{
		C->AddItemToBag(Slot, No, Count);
		Msg(FString::Printf(TEXT("Received: %s"), *C->GetItemName(Slot, No)));
		return true;
	}
	// Quest_SubITEM — take from the normal inventory.
	C->ConsumeBagItem(Slot, No, Count);
	return true;
}

// ─── conditions (F_QSTCOND*) ────────────────────────────────────────────────
bool URoseQuestComponent::CheckCondition(const TSharedPtr<FJsonObject>& Cond, FParam& Param)
{
	const int32 Type = JInt(Cond, TEXT("type"));
	const TArray<TSharedPtr<FJsonValue>>* Arr = nullptr;

	switch (Type)
	{
	case 0: // select quest slot by SN
	{
		const int32 Idx = FindQuestSlot(JInt(Cond, TEXT("questSN")));
		if (Idx < 0) return false;
		Param.SlotIdx = Idx;
		return true;
	}
	case 1: case 2: // quest var checks
		if (JArray(Cond, TEXT("vars"), Arr))
			for (const auto& V : *Arr)
			{
				const TSharedPtr<FJsonObject> D = V->AsObject();
				const int32 Val = GetQuestVar(Param, JInt(D, TEXT("varType")), JInt(D, TEXT("varNo")));
				if (Val == VarReadFailed) return false;
				if (!CheckOp(JInt(D, TEXT("op")), Val, JInt(D, TEXT("value")))) return false;
			}
		return true;
	case 3: // ability checks (AT_CLASS = job-set membership, Check_UserVAR)
		if (JArray(Cond, TEXT("abils"), Arr))
			for (const auto& V : *Arr)
			{
				const TSharedPtr<FJsonObject> D = V->AsObject();
				const int32 AbilType = JInt(D, TEXT("abilType"));
				if (AbilType == 4)
				{
					URoseSkillComponent* Sk = OwnerChar()
						? OwnerChar()->FindComponentByClass<URoseSkillComponent>() : nullptr;
					if (!Sk || !Sk->JobInClassSet(JInt(D, TEXT("value")))) return false;
					continue;
				}
				if (!CheckOp(JInt(D, TEXT("op")), GetAbility(AbilType), JInt(D, TEXT("value"))))
					return false;
			}
		return true;
	case 4: // item checks
		if (JArray(Cond, TEXT("items"), Arr))
			for (const auto& V : *Arr)
				if (!HasItemCheck(V->AsObject(), Param)) return false;
		return true;
	case 5: // party check — no party system: leader-required fails, level passes
		return JInt(Cond, TEXT("isLeader")) == 0;
	case 8: // quest remaining time
	{
		if (Param.SlotIdx < 0) return false;
		const int32 Remain = GetQuestVar(Param, 0x0200, 0);
		return CheckOp(JInt(Cond, TEXT("op")), Remain, JInt(Cond, TEXT("time")));
	}
	case 9: // skill known / not known in [skill1..skill2]
	{
		URoseSkillComponent* Sk = OwnerChar()
			? OwnerChar()->FindComponentByClass<URoseSkillComponent>() : nullptr;
		const int32 S1 = JInt(Cond, TEXT("skill1")), S2 = JInt(Cond, TEXT("skill2"));
		bool bHas = false;
		if (Sk)
			for (const auto& Pair : Sk->Learned)
				if (Pair.Value >= S1 && Pair.Value <= S2) { bHas = true; break; }
		return JInt(Cond, TEXT("op")) ? bHas : !bHas;
	}
	case 10: // random percent band (client-side roll)
	{
		const int32 R = FMath::RandRange(0, 100);
		return R >= JInt(Cond, TEXT("lowPct")) && R <= JInt(Cond, TEXT("highPct"));
	}
	case 14: // global switch
		return JInt(Cond, TEXT("op")) == GetUserSwitch(JInt(Cond, TEXT("sn")));
	case 15: // party member count — solo counts as 0..0
		return JInt(Cond, TEXT("n1")) <= 0 && JInt(Cond, TEXT("n2")) >= 0;
	case 23: // clan membership — no clan system: "not in a clan" passes
		return JInt(Cond, TEXT("reg")) == 0;

	// Server-side or unmodelled checks the classic CLIENT passes through as
	// true (obj vars 11/12/13/17, channel 22, radius 21) or that need systems
	// we don't have yet (world/zone time 7/16/18/19, position 6, clan 24-30).
	case 6: case 7: case 11: case 12: case 13: case 16: case 17: case 18:
	case 19: case 20: case 21: case 22: case 24: case 25: case 26: case 27:
	case 28: case 29: case 30:
		return true;
	}
	UE_LOG(LogRoseQuest, Warning, TEXT("unknown quest condition type %d"), Type);
	return true;
}

// ─── rewards (F_QSTREWD*) ────────────────────────────────────────────────────
bool URoseQuestComponent::ApplyReward(const TSharedPtr<FJsonObject>& Rewd, FParam& Param, bool bDoReward)
{
	ARoseCharacter* C = OwnerChar();
	if (!C) return false;
	const int32 Type = JInt(Rewd, TEXT("type"));
	const TArray<TSharedPtr<FJsonValue>>* Arr = nullptr;

	switch (Type)
	{
	case 0: // quest slot ops
	{
		if (!bDoReward) return true;
		const int32 QuestSN = JInt(Rewd, TEXT("questSN"));
		switch (JInt(Rewd, TEXT("op")))
		{
		case 0: // clear the SELECTED slot
			if (Param.SlotIdx < 0) return false;
			Slots[Param.SlotIdx].Reset();
			QuestRevision++;
			return true;
		case 1: // add — and, like the server (io_quest.cpp F_QSTREWD000 case 1),
		        // the new quest becomes the SELECTED slot when none is selected,
		        // so quest-item rewards later in the same trigger land in it.
		{
			const int32 NewIdx = AppendQuest(QuestSN);
			if (NewIdx < 0) return false;
			if (Param.SlotIdx < 0)
				Param.SlotIdx = NewIdx;
			return true;
		}
		case 2: // change the selected slot's id (keep progress)
			if (Param.SlotIdx < 0) return false;
			Slots[Param.SlotIdx].Id = QuestSN;
			QuestRevision++;
			return true;
		case 3: // reset + re-register into the selected slot
			if (Param.SlotIdx < 0) return false;
			Slots[Param.SlotIdx].Reset();
			Slots[Param.SlotIdx].Id = QuestSN;
			QuestRevision++;
			return true;
		case 4: // select
		{
			const int32 Idx = FindQuestSlot(QuestSN);
			if (Idx < 0) return false;
			Param.SlotIdx = Idx;
			return true;
		}
		}
		return true;
	}
	case 1: // give/take item
		if (!bDoReward) return true;
		return GiveOrTakeItem(JInt(Rewd, TEXT("itemSN")),
			FMath::Max(1, JInt(Rewd, TEXT("count"))),
			JInt(Rewd, TEXT("op")) == 1, Param);
	case 2: case 4: // set quest/char vars
		if (!bDoReward) return true;
		if (JArray(Rewd, TEXT("vars"), Arr))
			for (const auto& V : *Arr)
			{
				const TSharedPtr<FJsonObject> D = V->AsObject();
				const int32 VarType = JInt(D, TEXT("varType")), VarNo = JInt(D, TEXT("varNo"));
				const int32 Value = JInt(D, TEXT("value")), Op = JInt(D, TEXT("op"));
				const int32 Cur = GetQuestVar(Param, VarType, VarNo);
				if (Cur == VarReadFailed && VarType <= 0x0200) return false;
				switch (Op)
				{
				case 5: SetQuestVar(Param, VarType, VarNo, Value); break;       // set
				case 6: SetQuestVar(Param, VarType, VarNo, Cur + Value); break; // add
				case 7: SetQuestVar(Param, VarType, VarNo, Cur - Value); break; // sub
				case 8: SetQuestVar(Param, VarType, VarNo, 0); break;           // off
				case 9: SetQuestVar(Param, VarType, VarNo, 1); break;           // on
				}
			}
		return true;
	case 3: // set/adjust abilities
		if (!bDoReward) return true;
		if (JArray(Rewd, TEXT("abils"), Arr))
			for (const auto& V : *Arr)
			{
				const TSharedPtr<FJsonObject> D = V->AsObject();
				const int32 Op = JInt(D, TEXT("op"));
				AddAbility(JInt(D, TEXT("abilType")),
					Op == 7 ? -JInt(D, TEXT("value")) : JInt(D, TEXT("value")),
					/*bSet=*/Op == 5);
			}
		return true;
	case 5: // calculated exp/money/item (Get_RewardVALUE)
	{
		if (!bDoReward) return true;
		const int32 Target = JInt(Rewd, TEXT("target"));
		const int32 Eq = JInt(Rewd, TEXT("equation"));
		const int32 Base = JInt(Rewd, TEXT("value"));
		if (Target == 0)       // exp
		{
			AddAbility(30, RewardValue(Eq, Base, 0), false);
			return true;
		}
		if (Target == 1)       // money — dup count rides quest var 9
		{
			if (Param.SlotIdx < 0) return false;
			const int32 Dup = GetQuestVarBySlot(Param.SlotIdx, 9);
			C->AddZuly(RewardValue(Eq, Base, Dup));
			SetQuestVar(Param, 0x0000, 9, 0);
			Msg(TEXT("Received quest reward money."));
			return true;
		}
		if (Target == 2)       // item
		{
			const int32 ItemSN = JInt(Rewd, TEXT("itemSN"));
			const FString Slot = RoseItemTypeToSlot(ItemSN / 1000);
			const int32 Cnt = RoseIsStackableSlot(Slot)
				? FMath::Max(1, RewardValue(Eq, Base, 0)) : 1;
			return GiveOrTakeItem(ItemSN, Cnt, true, Param);
		}
		return false;
	}
	case 6: // heal HP/MP percent
		if (!bDoReward) return true;
		C->CurrentHP = FMath::Max(1.f, C->GetMaxHPStat() * JInt(Rewd, TEXT("hpPct")) / 100.f);
		C->CurrentMP = FMath::Max(1.f, C->GetMaxMPStat() * JInt(Rewd, TEXT("mpPct")) / 100.f);
		return true;
	case 9: // jump to another trigger
		Param.NextTrigger = JStr(Rewd, TEXT("nextTrigger"));
		return !Param.NextTrigger.IsEmpty();
	case 10: // Reward_InitSTATUS — reset base stats + restore point pool
		if (!bDoReward) return true;
		C->Strength = C->Dexterity = C->Intelligence = C->Concentration = 15;
		C->Charm = C->Sense = 15;
		C->ApplyDerivedStats();
		Msg(TEXT("Your stats have been reset."));
		return true;
	case 12: // npc message → chat
		if (bDoReward)
		{
			const FString Text = JStr(Rewd, TEXT("msg"));
			if (!Text.IsEmpty()) FRoseChatLog::Add(FRoseChatLog::EKind::Say, Text);
		}
		return true;
	case 14: // learn/forget skill
	{
		if (!bDoReward) return true;
		URoseSkillComponent* Sk = C->FindComponentByClass<URoseSkillComponent>();
		if (!Sk) return false;
		const int32 SkillNo = JInt(Rewd, TEXT("skillNo"));
		if (JInt(Rewd, TEXT("op")))
			return Sk->LearnSkill(SkillNo, /*bIgnoreChecks=*/true);
		Sk->Learned.Remove(SkillNo);   // forget (rare; base-row keyed)
		return true;
	}
	case 15: // global switch
		if (!bDoReward) return true;
		{
			const int32 SN = JInt(Rewd, TEXT("sn"));
			if (SN >= 0 && SN < Switches.Num())
			{
				Switches[SN] = JInt(Rewd, TEXT("op")) != 0;
				QuestRevision++;
			}
		}
		return true;
	case 16: // clear a 32-switch group
		if (!bDoReward) return true;
		{
			const int32 Group = JInt(Rewd, TEXT("groupSN"));
			for (int32 i = Group * 32; i < (Group + 1) * 32 && i < Switches.Num(); ++i)
				Switches[i] = false;
			QuestRevision++;
		}
		return true;

	case 7: // teleport — zone = LIST_ZONE row id; x/y = ABSOLUTE ROSE world
	        // units (520000-centred).  UE placement is X = x, Y = -y (see
	        // export_portals.py / the map importer).  Same mechanics as
	        // ARoseWarpPortal: same-zone = ground-snapped move, cross-zone =
	        // OpenLevel with the arrival point in the level options.
	{
		if (!bDoReward) return true;
		const int32 ZoneId = JInt(Rewd, TEXT("zone"));
		const FString Key = FZoneTable::Get().Keys.FindRef(ZoneId);
		if (Key.IsEmpty())
		{
			Msg(FString::Printf(TEXT("Quest warp failed: unknown zone %d."), ZoneId));
			return true;
		}
		const FString Level = TEXT("L_") + Key;
		if (!FPackageName::DoesPackageExist(
				FString::Printf(TEXT("/Game/Maps/%s/%s"), *Key, *Level)))
		{
			Msg(FString::Printf(TEXT("Quest warp: zone %s is not available."), *Key));
			return true;
		}
		const int32 RX = JInt(Rewd, TEXT("x"));
		const int32 RY = JInt(Rewd, TEXT("y"));
		const bool bHasPoint = RX != 0 || RY != 0;   // 0,0 = zone default start
		const float UEX = RX;
		const float UEY = -RY;
		UWorld* W = C->GetWorld();
		if (W->GetMapName().EndsWith(Level))
		{
			if (bHasPoint)
			{
				float Z = C->GetActorLocation().Z;
				FHitResult Hit;
				if (W->LineTraceSingleByChannel(Hit,
						FVector(UEX, UEY, Z + 5000.f), FVector(UEX, UEY, Z - 10000.f),
						ECC_Visibility))
					Z = Hit.ImpactPoint.Z;
				C->SetActorLocation(FVector(UEX, UEY, Z + 100.f));
			}
			return true;
		}
		URoseGameInstance::WarpToLevel(C, Level,
			bHasPoint ? FString::Printf(TEXT("WarpX=%.0f?WarpY=%.0f"), UEX, UEY)
			          : FString());
		return true;
	}

	// Server-side rewards the classic client acks as true (8 spawns, 11 obj
	// vars, 13 delayed triggers, 17-34 misc).
	case 8: case 11: case 13: case 17: case 18: case 19: case 20:
	case 21: case 22: case 23: case 24: case 25: case 26: case 27: case 28:
	case 29: case 30: case 31: case 32: case 33: case 34:
		return true;
	}
	UE_LOG(LogRoseQuest, Warning, TEXT("unknown quest reward type %d"), Type);
	return true;
}

// ─── the trigger walker (CheckQUEST + CQuestTRIGGER::Proc) ──────────────────
bool URoseQuestComponent::ProcTrigger(const TSharedPtr<FJsonObject>& Trigger, FParam& Param, bool bDoReward)
{
	const TArray<TSharedPtr<FJsonValue>>* Arr = nullptr;
	if (Trigger->TryGetArrayField(TEXT("conditions"), Arr))
		for (const auto& V : *Arr)
			if (!CheckCondition(V->AsObject(), Param))
				return false;
	if (Trigger->TryGetArrayField(TEXT("rewards"), Arr))
		for (const auto& V : *Arr)
			if (!ApplyReward(V->AsObject(), Param, bDoReward))
				return false;
	return true;
}

ERoseQuestResult URoseQuestComponent::CheckQuestTrigger(const FString& TriggerName, bool bDoReward)
{
	FQuestDB& DB = FQuestDB::Get();
	TSharedPtr<FJsonObject>* Found = DB.Triggers.Find(TriggerName);
	if (!Found)
	{
		UE_LOG(LogRoseQuest, Warning, TEXT("unknown quest trigger '%s'"), *TriggerName);
		return ERoseQuestResult::Invalid;
	}

	ERoseQuestResult Result = ERoseQuestResult::Invalid;
	FParam Param;
	TSharedPtr<FJsonObject> Trigger = *Found;
	FString Name = TriggerName;
	int32 Guard = 0;   // the data is authored acyclic; guard anyway

	while (Trigger.IsValid() && ++Guard < 64)
	{
		Param.NextTrigger.Reset();
		if (ProcTrigger(Trigger, Param, bDoReward))
		{
			if (!Param.NextTrigger.IsEmpty())
			{
				Found = DB.Triggers.Find(Param.NextTrigger);
				Name = Param.NextTrigger;
				Trigger = Found ? *Found : nullptr;
				Param = FParam();
				Result = ERoseQuestResult::Success;
				continue;
			}
			UE_LOG(LogRoseQuest, Verbose, TEXT("trigger '%s' fired (reward=%d)"), *Name, bDoReward);
			return ERoseQuestResult::Success;
		}

		if (!JInt(Trigger, TEXT("checkNext")))
			break;
		const FString Next = JStr(Trigger, TEXT("next"));
		Found = Next.IsEmpty() ? nullptr : DB.Triggers.Find(Next);
		Name = Next;
		Trigger = Found ? *Found : nullptr;
	}

	return Result;
}

FString URoseQuestComponent::DescribeState() const
{
	FString S = TEXT("Quests:");
	for (int32 i = 0; i < Slots.Num(); ++i)
	{
		if (!Slots[i].Id) continue;
		const FRoseQuestRow* Row = GetQuestRow(Slots[i].Id);
		S += FString::Printf(TEXT("\n  [%d] %d %s vars="), i, Slots[i].Id,
			Row ? *Row->DisplayName : TEXT("?"));
		for (int32 V : Slots[i].Vars) S += FString::Printf(TEXT("%d,"), V);
		for (const FRoseQuestItem& It : Slots[i].Items)
			S += FString::Printf(TEXT(" item %d x%d"), It.ItemSN, It.Quantity);
	}
	int32 OnSwitches = 0;
	for (int32 i = 0; i < Switches.Num(); ++i) if (Switches[i]) OnSwitches++;
	S += FString::Printf(TEXT("\n  switches on: %d, episode: %d %d %d %d %d"),
		OnSwitches, EpisodeVars[0], EpisodeVars[1], EpisodeVars[2], EpisodeVars[3], EpisodeVars[4]);
	return S;
}
