// DataTable row struct for the NPC/monster table (RoseUE/DataTables/npcs.csv,
// generated by tools/gen_npc_table.py from LIST_NPC.STB — column map per
// src/common/include/rose/io/stb.h).  Row key = "npc_<id>"; id == LIST_NPC.CHR
// model index == the imported /Game/Monsters/npc_<id> asset.  Data-driven:
// add/tune monsters by regenerating the CSV — never by editing code.
#pragma once

#include "CoreMinimal.h"
#include "Engine/DataTable.h"
#include "RoseNpcTypes.generated.h"

USTRUCT(BlueprintType)
struct FRoseNpcRow : public FTableRowBase
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   Id = 0;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) FString DisplayName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   WalkSpeed = 200;      // cm/s
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   RunSpeed = 400;       // cm/s
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   Scale = 100;          // percent (NPC_SCALE/100 = model scale)
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   Level = 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   HP = 10;              // per-level: MaxHP = HP * Level (cobjchar.cpp)
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   Attack = 1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   Hit = 50;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   Defense = 0;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   Resist = 0;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   Avoid = 0;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   AttackSpeed = 100;    // 100 = normal rate
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   IsMagicDamage = 0;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   AiType = 0;           // FILE_AI.STB row (AIP)
	// Held weapon models (LIST_NPC cols 5/6): LIST_WEAPON / LIST_SUBWPN item ids
	// attached to the CHR skeleton's hand dummies (guards' spears, boss blades).
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   RWeapon = 0;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   LWeapon = 0;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   GiveExp = 0;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   DropType = 0;    // ITEM_DROP.STB row
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   DropMoney = 0;   // money-drop chance 1-100
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   DropItem = 0;    // drop rate / quality (NPC_DROP_ITEM)
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   CanTarget = 0;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   AttackRange = 190;    // cm
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   NpcType = 0;
	// Sounds (FILE_SOUND rows / LIST_HITSOUND material column, RoseSoundData.h)
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   HitMaterial = 0;      // 0 flesh / 1 hard / 2 metal
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   AttackSound = 0;      // swing start
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   DieSound = 0;
	// Store tabs (NPC_SELL_TAB cols 21-24 → stores table rows; 0 = none).
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   SellTab0 = 0;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   SellTab1 = 0;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   SellTab2 = 0;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32   SellTab3 = 0;
	// On-death quest trigger (NPC_DESC col 41): CObjMOB::Do_DeadEvent fires
	// QF_doQuestTrigger with this name (kill-count quests).
	UPROPERTY(EditAnywhere, BlueprintReadOnly) FString QuestTrigger;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) FString Mesh;                 // UE asset path
	UPROPERTY(EditAnywhere, BlueprintReadOnly) FString StlKey;
};
