// ROSE PAT (vehicle) data types.
//
// ROSE has three distinct PAT features and LIST_PAT.STB names them itself in
// col 72 "PAT Class (1:Cart, 2:CG)":
//
//   Cart        assembled from 5 parts (t_eRidePART), burns fuel, rider visible
//   CastleGear  assembled from 5 parts, burns fuel
//   Mount       standalone single item — no parts, no fuel
//
// Rows are generated by tools/gen_pat_tables.py into DataTables/pat_parts.csv
// and DataTables/pat_motion.csv.
#pragma once

#include "CoreMinimal.h"
#include "Engine/DataTable.h"
#include "RosePatTypes.generated.h"

UENUM(BlueprintType)
enum class ERosePatClass : uint8
{
	None       = 0,
	Cart       = 1,
	CastleGear = 2,
	Mount      = 3,
};

// enumCART_ANI / enumPETMODE_AVATAR_ANI (src/client/cobjcart.h) — one shared
// order: the vehicle and its rider index their own motion rows with it.
UENUM(BlueprintType)
enum class ERosePatAnim : uint8
{
	Stop1     = 0,
	Move      = 1,
	Attack01  = 2,
	Attack02  = 3,
	Attack03  = 4,
	Die       = 5,
	Special01 = 6,
	Special02 = 7,
};

// t_eRidePART (src/common/shared/datatype.h)
enum { RIDE_PART_BODY = 0, RIDE_PART_ENGINE, RIDE_PART_LEG,
       RIDE_PART_ABIL, RIDE_PART_ARMS, MAX_RIDING_PART };

// TYPE_MOTION row bases used when an item's own row resolves to nothing. The
// 83 mounts whose PAT Motion is 625/626 point past the end of TYPE_MOTION, so
// they borrow the cart clips (they ride the cart skeleton either way).
enum { PAT_FALLBACK_VEHICLE_ROW = 281, PAT_FALLBACK_RIDER_ROW = 261 };

// pat_parts.csv — one LIST_PAT item.
USTRUCT(BlueprintType)
struct FRosePatPartRow : public FTableRowBase
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32 Id = 0;
	// LIST_PAT col 72: 1 cart, 2 castle gear, 3 mount
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32 PatClass = 0;
	// col 16 "Part Type" — 21 cart family, 31 castle gear family
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32 PartType = 0;
	// t_eRidePART slot (0..4); mounts are forced to BODY
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32 PartSlot = -1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32 ItemType = 0;

	// Fuel lives on the ENGINE part; mounts carry none.
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32 MaxFuel = 0;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32 FuelRate = 0;
	// Percent of base speed for cart/CG parts; an absolute speed for mounts.
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32 MoveSpeed = 0;

	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32 AtkRange = 0;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32 AtkPower = 0;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32 AtkSpeed = 0;

	// BODY rows carry the motion ROW base; ARMS rows carry the motion COLUMN.
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32 PatMotion = -1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32 AvatarMotion = -1;

	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32 Scale = 100;      // percent
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32 HidePlayer = 0;   // morph-style mounts
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32 HpGauge = 0;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32 StopSound = 0;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32 MoveSound = 0;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32 HasModel = 0;
};

// pat_motion.csv — one resolved TYPE_MOTION cell, keyed "m_<row>_<col>".
USTRUCT(BlueprintType)
struct FRosePatMotionRow : public FTableRowBase
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32 MotionRow = 0;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) int32 MotionCol = 0;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) FString Action;
	// ZMO stem == the glTF track name == the imported AnimSequence suffix
	UPROPERTY(EditAnywhere, BlueprintReadOnly) FString AnimName;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) FString ZmoPath;
};
