#!/usr/bin/env python3
"""
gen_sound_data.py — Generate the ROSE sound bindings:

  1. Source/RoseUE/RoseSoundData.h
       RoseSoundAssetPath(id)   FILE_SOUND.STB row -> imported /Game/Sounds asset
       RoseHitSound(type, mat)  LIST_HITSOUND.STB matrix -> FILE_SOUND row
                                (client: HIT_SOUND(WEAPON_ATK_HIT_SOUND(wpn),
                                 NPC_HIT_MATERIAL_TYPE(mob)); players are mat 1)
       ROSE_BAREHAND_*          LIST_WEAPON row 0 sound cols (unarmed attacker)
       RosePlaySoundId(...)     load + PlaySoundAtLocation helper
  2. tools/_tmp/sound_manifest.json — wav abs path -> asset path, consumed by
     ue5_import_sounds.py so the header and the imported assets always agree.

Only rows whose WAV exists on disk (client/Sound) get an asset path.

Usage:  py -3.9 gen_sound_data.py
"""
import json
import os
import re
import sys

_T = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _T)
from rose_parser.formats.stb import parse as parse_stb

# Asset source: Arua (CLAUDE.md "Asset source: Arua, always").  Was the
# deprecated SourceAssets/3DDATA classic tree; ZSC object ids and STB row
# ids do not line up across eras, so a row resolved to different content
# than the Arua-era DataTables this feeds.  Output roots are unchanged.
STB = os.path.join(os.environ.get("ROSE_ASSET_ROOT", r"C:\QQ-iROSE Online\extracted\3DDATA"), "STB")
CLIENT = r"C:/QQ-iROSE Online"                   # FILE_SOUND paths are client-relative
OUT_H = r"C:/rose-next-classic/unreal-engine rose/RoseUE/Source/RoseUE/RoseSoundData.h"
OUT_MANIFEST = os.path.join(_T, "_tmp", "sound_manifest.json")
GAME_ROOT = "/Game/Sounds"


def sanitize(part: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", part)


def asset_path(rel_wav: str) -> str:
    """'Sound\\mob\\Mob12_D.wav' -> '/Game/Sounds/mob/Mob12_D' (sanitized)."""
    parts = [p for p in rel_wav.replace("\\", "/").split("/") if p]
    if parts and parts[0].lower() == "sound":
        parts = parts[1:]
    parts[-1] = os.path.splitext(parts[-1])[0]
    return GAME_ROOT + "/" + "/".join(sanitize(p) for p in parts)


def main():
    snd = parse_stb(os.path.join(STB, "FILE_SOUND.STB"))
    hit = parse_stb(os.path.join(STB, "LIST_HITSOUND.STB"))
    wpn = parse_stb(os.path.join(STB, "LIST_WEAPON.STB"))

    paths = []       # index = FILE_SOUND row id
    manifest = {}
    missing = 0
    for i in range(snd.num_rows()):
        rel = snd.get(i, 0).strip()
        if not rel:
            paths.append(None)
            continue
        abs_wav = os.path.normpath(os.path.join(CLIENT, rel.replace("\\", os.sep)))
        if not os.path.isfile(abs_wav):
            paths.append(None)
            missing += 1
            continue
        ap = asset_path(rel)
        paths.append(ap)
        manifest[abs_wav] = ap

    n_hit_rows = hit.num_rows()
    hit_rows = [[hit.get_int(r, c) for c in range(3)] for r in range(n_hit_rows)]

    bare_start = wpn.get_int(0, 40)   # WEAPON_ATK_START_SOUND(0)
    bare_type = wpn.get_int(0, 42)    # WEAPON_ATK_HIT_SOUND(0) — hit-sound TYPE

    lines = []
    w = lines.append
    w("// GENERATED by tools/gen_sound_data.py — do not edit.")
    w("// ROSE combat sound bindings: FILE_SOUND.STB rows -> /Game/Sounds assets,")
    w("// the LIST_HITSOUND.STB (weapon hit type x defender material) matrix, and")
    w("// the bare-hand sound constants (LIST_WEAPON row 0).")
    w("#pragma once")
    w("")
    w("#include \"CoreMinimal.h\"")
    w("#include \"Kismet/GameplayStatics.h\"")
    w("#include \"Sound/SoundBase.h\"")
    w("")
    w(f"#define ROSE_BAREHAND_ATK_START_SOUND {bare_start}")
    w(f"#define ROSE_BAREHAND_HIT_TYPE {bare_type}")
    w("")
    w(f"static const int32 RoseSoundCount = {len(paths)};")
    w("static const TCHAR* const RoseSoundPaths[] = {")
    for p in paths:
        w(f"\tTEXT(\"{p}\")," if p else "\tnullptr,")
    w("};")
    w("")
    w(f"static const int16 RoseHitSoundTable[{n_hit_rows}][3] = {{")
    for row in hit_rows:
        w("\t{%d, %d, %d}," % tuple(row))
    w("};")
    w("")
    w("inline const TCHAR* RoseSoundAssetPath(int32 Id)")
    w("{")
    w("\treturn (Id > 0 && Id < RoseSoundCount) ? RoseSoundPaths[Id] : nullptr;")
    w("}")
    w("")
    w("// HIT_SOUND(T, I): weapon hit-sound type x defender material -> sound id.")
    w("// Players take material 1 (cobjchar_actionframe.cpp).")
    w("inline int32 RoseHitSound(int32 Type, int32 Material)")
    w("{")
    w(f"\tif (Type < 0 || Type >= {n_hit_rows}) return 0;")
    w("\treturn RoseHitSoundTable[Type][FMath::Clamp(Material, 0, 2)];")
    w("}")
    w("")
    w("// Load the row's imported wav and play it at a world position.")
    w("inline void RosePlaySoundId(UWorld* World, int32 Id, const FVector& At)")
    w("{")
    w("\tconst TCHAR* Path = RoseSoundAssetPath(Id);")
    w("\tif (!World || !Path) return;")
    w("\tconst FString Full = FString::Printf(TEXT(\"%s.%s\"), Path, *FPaths::GetBaseFilename(Path));")
    w("\tif (USoundBase* S = LoadObject<USoundBase>(nullptr, *Full))")
    w("\t\tUGameplayStatics::PlaySoundAtLocation(World, S, At);")
    w("}")
    w("")

    with open(OUT_H, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    os.makedirs(os.path.dirname(OUT_MANIFEST), exist_ok=True)
    with open(OUT_MANIFEST, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=1)

    print(f"[sound] {len(manifest)} wavs resolved ({missing} FILE_SOUND rows missing on disk)")
    print(f"[sound] header  -> {OUT_H}")
    print(f"[sound] manifest-> {OUT_MANIFEST}")
    print(f"[sound] barehand: start={bare_start} hit_type={bare_type}, "
          f"hit matrix {n_hit_rows}x3")


if __name__ == "__main__":
    main()
