#!/usr/bin/env python3
"""Generate Source/RoseUE/RoseSkillMotionData.h — per-skill cast/action anim.

Chain (ROSE authority, same as gen_weapon_motion.py but for the SKILL action
rows rather than the 7 loco/attack rows):
  LIST_SKILL.STB SKILL_ANI_ACTION_TYPE / SKILL_ANI_CASTING = a ROW in
  TYPE_MOTION.STB;  TYPE_MOTION[actionRow][weaponMotionType] = a FILE_MOTION
  index;  FILE_MOTION[idx][gender] = the ZMO (col 1 Female -> fallback col 0
  Male).  The imported UE AnimSequence is  base<ZMO_STEM_UPPER>.

Only the action rows actually referenced by skills.csv are emitted (compact):
a sorted row list + [rows][21 motion types] name tables for each gender, plus
RoseSkillActionAnim(motionType, actionRow, bFemale) doing a binary search.
"""
import os, sys, csv
_T = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _T)
from rose_parser.formats.stb import parse as parse_stb

# Asset source: Arua (CLAUDE.md).  TYPE_MOTION.STB is 626x28 in Arua vs 621x21
# in classic, and skills.csv is keyed to Arua rows — a classic-sourced motion
# row resolved to the wrong animation for a given skill.  SRC is the PARENT of
# 3DDATA because the joins below re-append it.
SRC = os.path.dirname(os.environ.get("ROSE_ASSET_ROOT",
                                     r"C:\QQ-iROSE Online\extracted\3DDATA"))
OUT = os.path.normpath(os.path.join(_T, "..", "unreal-engine rose", "RoseUE",
                                    "Source", "RoseUE", "RoseSkillMotionData.h"))
SKILLS_CSV = os.path.normpath(os.path.join(_T, "..", "unreal-engine rose", "RoseUE",
                                           "DataTables", "skills.csv"))

tm = parse_stb(os.path.join(SRC, "3DDATA", "STB", "TYPE_MOTION.STB"))
fm = parse_stb(os.path.join(SRC, "3DDATA", "STB", "FILE_MOTION.STB"))
N_MT = tm.num_cols()          # 21 weapon motion types (columns)


def asset(motion_idx, female):
    try:
        mi = int(motion_idx)
    except (TypeError, ValueError):
        return ""
    cell = (fm.get(mi, 1) or fm.get(mi, 0)) if female else fm.get(mi, 0)
    cell = (cell or "").strip()
    if not cell or cell == ".":
        return ""
    stem = os.path.splitext(os.path.basename(cell.replace("\\", "/")))[0]
    return "base" + stem.upper()


# distinct skill action rows (both the release ACTION and the CASTING pose)
rows = list(csv.DictReader(open(SKILLS_CSV, encoding="utf-8-sig")))
used = set()
for r in rows:
    for col in ("ActionMotion", "CastMotion"):
        try:
            a = int(r[col])
        except (TypeError, ValueError, KeyError):
            continue
        if 0 < a < tm.num_rows():
            used.add(a)
used = sorted(used)


def table(female):
    return [[asset(tm.get(a, mt), female) for mt in range(N_MT)] for a in used]


tf, tmm = table(True), table(False)


def emit(name, data):
    out = [f"static const TCHAR* const {name}[{len(used)}][{N_MT}] = {{"]
    for a, cells in zip(used, data):
        cs = ", ".join(f'TEXT("{c}")' for c in cells)
        out.append(f"\t{{ {cs} }},  // row {a}")
    out.append("};")
    return "\n".join(out)


with open(OUT, "w", encoding="utf-8") as f:
    f.write("// Generated by tools/gen_skill_motion.py — do not edit by hand.\n")
    f.write("// Skill SKILL_ANI_ACTION_TYPE / SKILL_ANI_CASTING (a TYPE_MOTION row)\n")
    f.write("// + the equipped weapon's Motion Type (column) -> base<ZMO> AnimSequence.\n")
    f.write("// Only rows referenced by skills.csv are emitted.\n")
    f.write("#pragma once\n#include \"CoreMinimal.h\"\n\n")
    f.write("static const int32 RoseSkillActionRows[%d] = { %s };\n\n"
            % (len(used), ", ".join(str(a) for a in used)))
    f.write(emit("RoseSkillMotionF", tf) + "\n\n")
    f.write(emit("RoseSkillMotionM", tmm) + "\n\n")
    f.write(
        "// Anim name for a skill action row played with weapon MotionType, per\n"
        "// gender; \"\" when the row is unknown or has no motion for that type.\n"
        "static const TCHAR* RoseSkillActionAnim(int32 MotionType, int32 ActionRow, bool bFemale)\n"
        "{\n"
        f"\tif (MotionType < 0 || MotionType >= {N_MT}) MotionType = 0;\n"
        f"\tint32 Lo = 0, Hi = {len(used)} - 1;\n"
        "\twhile (Lo <= Hi)\n\t{\n"
        "\t\tconst int32 Mid = (Lo + Hi) / 2;\n"
        "\t\tconst int32 R = RoseSkillActionRows[Mid];\n"
        "\t\tif (R == ActionRow)\n"
        "\t\t\treturn (bFemale ? RoseSkillMotionF : RoseSkillMotionM)[Mid][MotionType];\n"
        "\t\tif (R < ActionRow) Lo = Mid + 1; else Hi = Mid - 1;\n"
        "\t}\n"
        "\treturn TEXT(\"\");\n"
        "}\n")

print(f"wrote {OUT}")
print(f"  {len(used)} skill action rows x {N_MT} motion types x 2 genders")
